name: Build & Deploy product microservice

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    name: Build and Deploy product
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_USER: kata
          MYSQL_PASSWORD: passw0rd
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DB: ecommerce
        ports:
          - 3306:3306
        options: >-
          --health-cmd "pg_isready -U user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup jdk 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

